//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomToDoManager.FastService {
    using System.Runtime.Serialization;
    using System;
    using ToDo.Infrastructure;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomTask", Namespace="http://schemas.datacontract.org/2004/07/FastService")]
    [System.SerializableAttribute()]
    public partial class CustomTask : object,IToDoItem, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ToDoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCompleted {
            get {
                return this.IsCompletedField;
            }
            set {
                if ((this.IsCompletedField.Equals(value) != true)) {
                    this.IsCompletedField = value;
                    this.RaisePropertyChanged("IsCompleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ToDoId {
            get {
                return this.ToDoIdField;
            }
            set {
                if ((this.ToDoIdField.Equals(value) != true)) {
                    this.ToDoIdField = value;
                    this.RaisePropertyChanged("ToDoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FastService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncToDoItems", ReplyAction="http://tempuri.org/IService1/SyncToDoItemsResponse")]
        void SyncToDoItems(CustomToDoManager.FastService.CustomTask item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncToDoItems", ReplyAction="http://tempuri.org/IService1/SyncToDoItemsResponse")]
        System.Threading.Tasks.Task SyncToDoItemsAsync(CustomToDoManager.FastService.CustomTask item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncDeleteItem", ReplyAction="http://tempuri.org/IService1/SyncDeleteItemResponse")]
        void SyncDeleteItem(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncDeleteItem", ReplyAction="http://tempuri.org/IService1/SyncDeleteItemResponse")]
        System.Threading.Tasks.Task SyncDeleteItemAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncUpdateItem", ReplyAction="http://tempuri.org/IService1/SyncUpdateItemResponse")]
        void SyncUpdateItem(CustomToDoManager.FastService.CustomTask item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SyncUpdateItem", ReplyAction="http://tempuri.org/IService1/SyncUpdateItemResponse")]
        System.Threading.Tasks.Task SyncUpdateItemAsync(CustomToDoManager.FastService.CustomTask item);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CustomToDoManager.FastService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CustomToDoManager.FastService.IService1>, CustomToDoManager.FastService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SyncToDoItems(CustomToDoManager.FastService.CustomTask item) {
            base.Channel.SyncToDoItems(item);
        }
        
        public System.Threading.Tasks.Task SyncToDoItemsAsync(CustomToDoManager.FastService.CustomTask item) {
            return base.Channel.SyncToDoItemsAsync(item);
        }
        
        public void SyncDeleteItem(int id) {
            base.Channel.SyncDeleteItem(id);
        }
        
        public System.Threading.Tasks.Task SyncDeleteItemAsync(int id) {
            return base.Channel.SyncDeleteItemAsync(id);
        }
        
        public void SyncUpdateItem(CustomToDoManager.FastService.CustomTask item) {
            base.Channel.SyncUpdateItem(item);
        }
        
        public System.Threading.Tasks.Task SyncUpdateItemAsync(CustomToDoManager.FastService.CustomTask item) {
            return base.Channel.SyncUpdateItemAsync(item);
        }
    }
}
